### ISSUE TITLE
[Linux] Cannot load such file --rMeetup

### ISSUE THREAD

**Issue by schvabodka-man** [specious/meetup-cli#1]
Hi there! Simply installed this nice utility, trying to launch it and get
```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rMeetup (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/meetup-cli-1.0.7/lib/meetup-cli/api.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/meetup-cli-1.0.7/lib/meetup-cli.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/meetup-cli-1.0.7/bin/meetup-cli:5:in `<top (required)>'
	from /usr/local/bin/meetup-cli:22:in `load'
	from /usr/local/bin/meetup-cli:22:in `<main>'
```
That's weird because i've this library installed. My ruby version is 2.3.3, my gems version is 2.5.2. My os is Fedora 25

**Comment by specious** [comment]
I wonder what could be wrong with your [load path](http://guides.rubygems.org/rubygems-basics/#requiring-code).  Does `irb -rrMeetup` give you an error?

**Comment by schvabodka-man** [comment]
Yes it gives me that
`/usr/share/ruby/irb/init.rb:213:in `parse_opts': Unrecognized switch: --rrMeetup (IRB::UnrecognizedSwitch)
	from /usr/share/ruby/irb/init.rb:19:in `setup'
	from /usr/share/ruby/irb.rb:378:in `start'
	from /usr/bin/irb:11:in `<main>'
`

**Comment by specious** [comment]
Try one dash `-`, not two.

**Comment by schvabodka-man** [comment]
`/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require':LoadError: cannot load such file -- rMeetup`

**Comment by specious** [comment]
I'm still rather new to Ruby, so I'm learning all the different ways that the Ruby environment can be set up.  I'd like to figure out what is considered the best way globally install a Ruby app that would work well across different environments.

So far, I recommended `sudo gem install meetup-cli` because it works on OS X with a system-wide Ruby install, whereas `gem install meetup-cli` does not.

Did you install Ruby through a Ruby environment manager such as [rbenv](https://github.com/rbenv/rbenv) or [rvm](https://rvm.io/)?

**Comment by specious** [comment]
Perhaps on Fedora what would work is:
```
$ sudo dnf install ruby-devel
$ gem install meetup-cli
```

**Comment by schvabodka-man** [comment]
that's a way i'have installed it, but with sudo gem, because just gem gives me permissions error. I've installed Ruby environment through the standart package manager (dnf install ruby-devel).

**Comment by specious** [comment]
What's the output of `puts $LOAD_PATH` in `irb`?

**Comment by schvabodka-man** [comment]
Well it looks like that
[![asciicast](https://asciinema.org/a/2qcq8z2plgj9hp0pkav93cs47.png)](https://asciinema.org/a/2qcq8z2plgj9hp0pkav93cs47)

**Comment by specious** [comment]
Thank you so much for helping me troubleshoot this.

So, your $LOAD_PATH is:
```ruby
["/usr/share/gems/gems/did_you_mean-1.0.0/lib", "/usr/local/share/ruby/site_ruby",
"/usr/local/lib64/ruby/site_ruby", "/usr/share/ruby/vendor_ruby",
"/usr/lib64/ruby/vendor_ruby", "/usr/share/rubygems", "/usr/share/ruby", "/usr/lib64/ruby"] 
```

Could you post the output of `gem environment`?

**Comment by schvabodka-man** [comment]
I got this
[![asciicast](https://asciinema.org/a/261vwsyq68ihc6f5kx18sxe1o.png)](https://asciinema.org/a/261vwsyq68ihc6f5kx18sxe1o)

**Comment by specious** [comment]
It's easier to troubleshoot if you just post the output here.  So, your `gem environment` returns:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/user/.gem/ruby
  - USER INSTALLATION DIRECTORY: /home/user/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /home/user/bin
  - SPEC CACHE DIRECTORY: /home/user/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/user/.gem/ruby
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
```

Is your user name actually `user`?

**Comment by schvabodka-man** [comment]
Yeah, my name is user. But in fact i've isntalled meetup-cli as root(gem gives me access denied when using it without super user permissions). _I discovered this fancy tool for screencasts in cli, so i'm trying to find usecases for it_

**Comment by specious** [comment]
> I discovered this fancy tool for screencasts in cli, so i'm trying to find usecases for it

It's a fantastic product.  The frontend is notably [written in ClojureScript](https://github.com/asciinema/asciinema-player/tree/master/src/asciinema/player) and the [asciinema blog](http://blog.asciinema.org/) is quite informative.

However, it adds unnecessary difficulty when I'm trying to figure out a problem and I'm looking at this:

![scrn](https://cloud.githubusercontent.com/assets/451178/21966066/864bc0d8-db3a-11e6-8e9f-0094b80a6ff9.png)

**Comment by specious** [comment]
I'm still stumped on this issue.  Could you post the output of `gem list` and `gem spec rMeetup`?

**Comment by schvabodka-man** [comment]
Gem list:

`gem list

*** LOCAL GEMS ***

addressable (2.5.0)
bigdecimal (1.2.8)
buftok (0.2.0)
colorize (0.8.1)
did_you_mean (1.0.0)
domain_name (0.5.20161129)
gli (2.14.0)
http (0.9.9)
http-cookie (1.0.3)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
io-console (0.4.5)
json (1.8.3)
meetup-cli (1.0.7)
psych (2.1.0)
public_suffix (2.0.5)
rdoc (4.2.2)
rMeetup (2.1.0)
rmeetup (1.0.0)
unf (0.1.4)
unf_ext (0.0.7.2)
`

`gem spec rMeetup                                                 1984ms
--- !ruby/object:Gem::Specification
name: rMeetup
version: !ruby/object:Gem::Version
  version: 2.1.0
platform: ruby
authors:
- Jared Pace
- Jason Berlinsky
- Tommy Chan
- Tanner Mares
- Zishan Ahmad
- Nikica Jokić
autorequire: 
bindir: bin
cert_chain: []
date: 2015-01-21 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
  name: json
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '1.8'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '1.8'
- !ruby/object:Gem::Dependency
  name: buftok
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '0.2'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '0.2'
- !ruby/object:Gem::Dependency
  name: http
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '0.7'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '0.7'
- !ruby/object:Gem::Dependency
  name: http_parser.rb
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '0.6'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '0.6'
- !ruby/object:Gem::Dependency
  name: bundler
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '1.6'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '1.6'
description: meetup.com API wrapper for Ruby
email:
- jdpace@github.com
- jason@jasonberlinsky.com
- tommytcchan@gmail.com
- tannermares@gmail.com
- me@zishanahmad.com
- neektza@gmail.com
executables: []
extensions: []
extra_rdoc_files: []
files: []
homepage: https://github.com/floatingpointio/rmeetup
licenses:
- MIT
metadata: {}
post_install_message: 
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: 1.3.6
requirements: []
rubyforge_project: 
rubygems_version: 2.5.2
signing_key: 
specification_version: 4
summary: A Ruby wrapper for the Meetup API v2
test_files: []
`

**Comment by specious** [comment]
Thanks @schvabodka-man, I appreciate this.  I see you've got both `rMeetup` and `rmeetup` listed in `gem list`.  I presume you tried to `gem install rmeetup` to try to fix the problem.

@tjstankus helped me troubleshoot this situation last night at a local Ruby meetup, and we've arrived at a suspicion that the inconsistent capitalization of the name in the `rMeetup` gem might be causing the problem on case-sensitive file systems.

**Comment by specious** [comment]
I used a Docker VM running Alpine Linux to confirm the issue.  Indeed, the problem disappears when I change the `rMeetup` gem name to lower case:

```diff
--- a/lib/meetup-cli/api.rb
+++ b/lib/meetup-cli/api.rb
@@ -1,4 +1,4 @@
-require 'rMeetup'
+require 'rmeetup'
```

I [added](https://github.com/specious/meetup-cli/commit/f5c6aca9bd3b9c4f5744a9dd862b79d542a29379) my Dockerfile to the project.

**Comment by specious** [comment]
@tjstankus, thanks so much for helping me pin this down 👍

**Comment by schvabodka-man** [comment]
Big thanks to you! Now it works as supposed!
